'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';

export default function InstructorAssessments() {
  const [results, setResults] = useState([]);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState('performance');
  const [copyStatus, setCopyStatus] = useState('');
  const [exporterTab, setExporterTab] = useState('latex');
  const [expandedCard, setExpandedCard] = useState({});

  useEffect(() => {
    async function fetchData() {
      const userHeader = typeof window !== 'undefined' ? localStorage.getItem('session_user') || '' : '';
      const res = await fetch('/api/instructor/assessments', {
        headers: { 'x-user-id': userHeader }
      });
      if (res.ok) {
        const data = await res.json();
        setResults(data.results);
      }
      setLoading(false);
    }
    fetchData();
  }, []);

  if (loading) return <div className="container">Loading assessment data...</div>;

  const feedbacks = results.filter(r => r.evaluation_questionnaire);

  // Calculate aggregates
  const avgSatisfaction = feedbacks.length > 0 
    ? (feedbacks.reduce((sum, f) => sum + f.evaluation_questionnaire.satisfaction, 0) / feedbacks.length).toFixed(1)
    : '0.0';

  const q1YesRate = feedbacks.length > 0
    ? Math.round((feedbacks.filter(f => f.evaluation_questionnaire.q1_ai_helpful === 'Yes').length / feedbacks.length) * 100)
    : 0;

  const q2YesRate = feedbacks.length > 0
    ? Math.round((feedbacks.filter(f => f.evaluation_questionnaire.q2_difficulty_appropriate === 'Yes').length / feedbacks.length) * 100)
    : 0;

  const q3YesRate = feedbacks.length > 0
    ? Math.round((feedbacks.filter(f => f.evaluation_questionnaire.q3_recommend === 'Yes').length / feedbacks.length) * 100)
    : 0;

  const surveyQuestionsList = [
    // Section A
    { key: 'q_math_clear', section: 'Section A: UX & Usability', text: 'Mathematical equations and fractions were clear and easy to read.' },
    { key: 'q_dark_mode', section: 'Section A: UX & Usability', text: 'The dark-mode interface was comfortable to look at for extended periods.' },
    { key: 'q_navigation', section: 'Section A: UX & Usability', text: 'I found it easy to navigate between questions, hints, and scratchpad.' },
    // Section B
    { key: 'q_adaptation', section: 'Section B: Pedagogical & Adaptive Engine', text: 'The practice questions adapted well to my skill level (not too easy/hard).' },
    { key: 'q_hints', section: 'Section B: Pedagogical & Adaptive Engine', text: 'The hints provided by the system helped me solve questions I was stuck on.' },
    { key: 'q_improvement', section: 'Section B: Pedagogical & Adaptive Engine', text: 'I feel that my understanding of the math topics improved after using practice module.' },
    // Section C
    { key: 'q_ai_walkthrough', section: 'Section C: AI Interventions', text: 'When system stopped me after two wrong answers, AI walkthrough helped figure out mistakes.' },
    { key: 'q_ai_tone', section: 'Section C: AI Interventions', text: 'The tone of the AI tutor was encouraging and friendly.' },
    { key: 'q_ai_length', section: 'Section C: AI Interventions', text: 'The AI explanations were the right length (not too long or overwhelming).' },
    // Section D
    { key: 'q_timer_paused', section: 'Section D: Psychological Factors', text: 'Freezing the timer during the AI walkthrough helped me feel less stressed.' },
    { key: 'q_untimed', section: 'Section D: Psychological Factors', text: 'I liked that the assessments were untimed because it allowed me to think clearly.' },
    { key: 'q_confidence', section: 'Section D: Psychological Factors', text: 'Using this system made me feel more confident about tackling difficult math.' },
    // Section E
    { key: 'q_teach_me', section: 'Section E: Post-Assessment AI Review', text: 'Reviewing mistakes with "Teach Me!" button after test was a valuable way to learn.' },
    { key: 'q_study_plan', section: 'Section E: Post-Assessment AI Review', text: 'The custom study plan generated by the AI matched my actual weaknesses.' }
  ];

  const calculateDetailedStats = () => {
    if (feedbacks.length === 0) return [];
    return surveyQuestionsList.map(q => {
      const scores = feedbacks.map(f => {
        const val = f.evaluation_questionnaire[q.key];
        if (val !== undefined && val !== null) return Number(val);
        // Backward-compatibility fallback for legacy questionnaire submissions
        if (q.key === 'q_math_clear' || q.key === 'q_dark_mode' || q.key === 'q_navigation') {
          return Number(f.evaluation_questionnaire.satisfaction || 3);
        }
        if (q.key === 'q_ai_walkthrough') {
          return f.evaluation_questionnaire.q1_ai_helpful === 'Yes' ? 5 : 2;
        }
        if (q.key === 'q_adaptation') {
          return f.evaluation_questionnaire.q2_difficulty_appropriate === 'Yes' ? 5 : 2;
        }
        if (q.key === 'q_confidence') {
          return f.evaluation_questionnaire.q3_recommend === 'Yes' ? 5 : 2;
        }
        return 3;
      });

      const n = scores.length;
      const sum = scores.reduce((a, b) => a + b, 0);
      const mean = sum / n;
      const variance = scores.reduce((s, x) => s + Math.pow(x - mean, 2), 0) / n;
      const sd = Math.sqrt(variance);
      const positiveRate = (scores.filter(x => x >= 4).length / n) * 100;

      return {
        ...q,
        mean: mean.toFixed(2),
        sd: sd.toFixed(2),
        agreement: Math.round(positiveRate)
      };
    });
  };

  const detailedStats = calculateDetailedStats();

  const getLaTeXCode = () => {
    let code = `% LaTeX Table Code for Thesis (N = ${feedbacks.length})\n`;
    code += `\\begin{table}[h]\n`;
    code += `\\centering\n`;
    code += `\\caption{Student Questionnaire Survey Statistics ($N = ${feedbacks.length}$)}\n`;
    code += `\\label{tab:survey_stats}\n`;
    code += `\\begin{tabular}{lccc}\n`;
    code += `\\hline\n`;
    code += `\\textbf{Survey Question Item (7-8 Grade Simp)} & \\textbf{Mean (1-5)} & \\textbf{S.D.} & \\textbf{Agreement (\\%)} \\\\\n`;
    code += `\\hline\n`;
    
    let currentSec = '';
    detailedStats.forEach(s => {
      if (s.section !== currentSec) {
        currentSec = s.section;
        code += `\\hline\n\\multicolumn{4}{l}{\\textbf{${currentSec}}} \\\\\n\\hline\n`;
      }
      const escaped = s.text.replace(/%/g, '\\%').replace(/&/g, '\\&');
      code += `${escaped} & ${s.mean} & ${s.sd} & ${s.agreement}\% \\\\\n`;
    });
    
    code += `\\hline\n`;
    code += `\\end{tabular}\n`;
    code += `\\end{table}`;
    return code;
  };

  const getMarkdownCode = () => {
    let code = `### Student Questionnaire Survey Statistics (N = ${feedbacks.length})\n\n`;
    code += `| Section | Survey Question Item | Mean Score (1-5) | Standard Dev. (S.D.) | Agreement (Score >= 4) |\n`;
    code += `| --- | --- | --- | --- | --- |\n`;
    detailedStats.forEach(s => {
      code += `| ${s.section} | ${s.text} | ${s.mean} | ${s.sd} | ${s.agreement}% |\n`;
    });
    return code;
  };

  const getCSVCode = () => {
    let code = `Section,Question Item,Mean,Standard Deviation,Agreement Rate\n`;
    detailedStats.forEach(s => {
      code += `"${s.section}","${s.text.replace(/"/g, '""')}",${s.mean},${s.sd},${s.agreement}%\n`;
    });
    return code;
  };

  const copyToClipboard = (text, type) => {
    navigator.clipboard.writeText(text);
    setCopyStatus(type);
    setTimeout(() => setCopyStatus(''), 2000);
  };

  const toggleCard = (i) => {
    setExpandedCard(prev => ({
      ...prev,
      [i]: !prev[i]
    }));
  };

  return (
    <div className="container">
      <header className="page-header">
        <h1 className="title">Assessment & Feedback Portal</h1>
        <p className="subtitle">Track pre/post test gains alongside student satisfaction and qualitative reviews.</p>
      </header>

      {/* Navigation Tabs */}
      <div style={{ display: 'flex', gap: '5px', marginBottom: '25px', borderBottom: '1px solid rgba(255, 255, 255, 0.08)', paddingBottom: '0' }}>
        <button
          onClick={() => setActiveTab('performance')}
          style={{
            padding: '12px 24px',
            border: 'none',
            fontWeight: '600',
            fontSize: '0.95rem',
            cursor: 'pointer',
            background: 'transparent',
            color: activeTab === 'performance' ? '#a855f7' : '#9ca3af',
            borderBottom: activeTab === 'performance' ? '2px solid #a855f7' : '2px solid transparent',
            transition: 'all 0.2s',
            outline: 'none'
          }}
        >
          <i className="fa-solid fa-chart-simple" style={{ marginRight: '8px' }}></i> Assessment Performance
        </button>
        <button
          onClick={() => setActiveTab('feedback')}
          style={{
            padding: '12px 24px',
            border: 'none',
            fontWeight: '600',
            fontSize: '0.95rem',
            cursor: 'pointer',
            background: 'transparent',
            color: activeTab === 'feedback' ? '#a855f7' : '#9ca3af',
            borderBottom: activeTab === 'feedback' ? '2px solid #a855f7' : '2px solid transparent',
            transition: 'all 0.2s',
            outline: 'none'
          }}
        >
          <i className="fa-solid fa-comments" style={{ marginRight: '8px' }}></i> Student Feedbacks ({feedbacks.length})
        </button>
        <button
          onClick={() => setActiveTab('thesis')}
          style={{
            padding: '12px 24px',
            border: 'none',
            fontWeight: '600',
            fontSize: '0.95rem',
            cursor: 'pointer',
            background: 'transparent',
            color: activeTab === 'thesis' ? '#a855f7' : '#9ca3af',
            borderBottom: activeTab === 'thesis' ? '2px solid #a855f7' : '2px solid transparent',
            transition: 'all 0.2s',
            outline: 'none'
          }}
        >
          <i className="fa-solid fa-graduation-cap" style={{ marginRight: '8px' }}></i> 🎓 Thesis Analytics (Survey Stats)
        </button>
      </div>

      {activeTab === 'performance' && (
        <div className="card" style={{padding: '0', overflow: 'hidden'}}>
          <table style={{width: '100%', borderCollapse: 'collapse', textAlign: 'left'}}>
            <thead style={{background: 'var(--highlight)', borderBottom: '1px solid var(--border)'}}>
              <tr>
                <th style={{padding: '16px 24px'}}>Student</th>
                <th style={{padding: '16px 24px'}}>Pre-Test</th>
                <th style={{padding: '16px 24px'}}>Post-Test</th>
                <th style={{padding: '16px 24px'}}>Improvement (Delta)</th>
                <th style={{padding: '16px 24px'}}>Status</th>
              </tr>
            </thead>
            <tbody>
              {results.map((res, i) => (
                <tr key={i} style={{borderBottom: '1px solid var(--border)'}}>
                  <td style={{padding: '16px 24px', fontWeight: 600}}>
                    <Link href={`/instructor/student-detail?student=${res.username}`} style={{ color: 'var(--primary)', textDecoration: 'none', display: 'inline-flex', alignItems: 'center', gap: '8px' }}>
                      <i className="fa-solid fa-chart-line" style={{ fontSize: '0.9rem', opacity: 0.8 }}></i>
                      {res.username}
                    </Link>
                  </td>
                  <td style={{padding: '16px 24px'}}>
                    {res.pre_completed ? `${res.pre_score}%` : <span style={{color: 'var(--muted)'}}>Not Started</span>}
                  </td>
                  <td style={{padding: '16px 24px'}}>
                    {res.post_completed ? `${res.post_score}%` : <span style={{color: 'var(--muted)'}}>{res.pre_completed ? 'In Progress' : 'Pending'}</span>}
                  </td>
                  <td style={{padding: '16px 24px'}}>
                    {res.delta !== null ? (
                      <span style={{
                        fontWeight: 700, 
                        color: res.delta >= 0 ? 'var(--success-text)' : 'var(--warn-text)',
                        display: 'inline-flex',
                        alignItems: 'center',
                        gap: '4px'
                      }}>
                        <i className={`fa-solid ${res.delta >= 0 ? 'fa-arrow-trend-up' : 'fa-arrow-trend-down'}`}></i>
                        {res.delta > 0 ? `+${res.delta}` : res.delta}%
                      </span>
                    ) : '--'}
                  </td>
                  <td style={{padding: '16px 24px'}}>
                    {res.delta !== null ? (
                      res.delta > 0 ? (
                        <span className="status success show" style={{display: 'inline-block', margin: 0, padding: '4px 12px'}}>Improved!</span>
                      ) : res.delta === 0 ? (
                        <span className="status show" style={{display: 'inline-block', margin: 0, padding: '4px 12px', background: 'var(--highlight)', color: 'var(--text)'}}>No Change</span>
                      ) : (
                        <span className="status warn show" style={{display: 'inline-block', margin: 0, padding: '4px 12px'}}>Needs Review</span>
                      )
                    ) : (
                      <span style={{color: 'var(--muted)', fontSize: '0.9rem'}}>Pending Completion</span>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {activeTab === 'feedback' && (
        <div>
          {feedbacks.length === 0 ? (
            <div className="card" style={{textAlign: 'center', padding: '60px'}}>
              <i className="fa-solid fa-comments-dashed" style={{fontSize: '3rem', color: 'var(--muted)', marginBottom: '16px'}}></i>
              <h3>No submitted questionnaire feedback yet</h3>
              <p style={{color: 'var(--muted)'}}>Once students complete their post-assessment and submit evaluations, they will appear here.</p>
            </div>
          ) : (
            <>
              {/* Aggregates Dashboard */}
              <div className="grid" style={{marginBottom: '30px', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '20px'}}>
                <div className="card" style={{textAlign: 'center', padding: '20px', background: 'rgba(168, 85, 247, 0.05)', border: '1px solid rgba(168, 85, 247, 0.15)'}}>
                  <h3 style={{color: 'var(--muted)', margin: '0 0 8px', fontSize: '0.95rem'}}>Class Satisfaction</h3>
                  <p style={{fontSize: '2.5rem', fontWeight: 700, margin: '0 0 4px', color: '#a855f7'}}>{avgSatisfaction} <span style={{fontSize: '1.2rem', color: 'var(--muted)'}}>/ 5</span></p>
                  <div style={{color: '#a855f7', fontSize: '1rem'}}>
                    {Array.from({ length: 5 }).map((_, i) => (
                      <i key={i} className={`fa-${Math.round(Number(avgSatisfaction)) > i ? 'solid' : 'regular'} fa-star`} style={{marginRight: '2px'}}></i>
                    ))}
                  </div>
                </div>
                <div className="card" style={{textAlign: 'center', padding: '20px'}}>
                  <h3 style={{color: 'var(--muted)', margin: '0 0 8px', fontSize: '0.95rem'}}>AI Helpful Rate</h3>
                  <p style={{fontSize: '2.5rem', fontWeight: 700, margin: '0 0 4px', color: '#10b981'}}>{q1YesRate}%</p>
                  <p style={{color: 'var(--muted)', fontSize: '0.8rem', margin: 0}}>of students selected "Yes"</p>
                </div>
                <div className="card" style={{textAlign: 'center', padding: '20px'}}>
                  <h3 style={{color: 'var(--muted)', margin: '0 0 8px', fontSize: '0.95rem'}}>Appropriate Pace</h3>
                  <p style={{fontSize: '2.5rem', fontWeight: 700, margin: '0 0 4px', color: '#38bdf8'}}>{q2YesRate}%</p>
                  <p style={{color: 'var(--muted)', fontSize: '0.8rem', margin: 0}}>of students selected "Yes"</p>
                </div>
                <div className="card" style={{textAlign: 'center', padding: '20px'}}>
                  <h3 style={{color: 'var(--muted)', margin: '0 0 8px', fontSize: '0.95rem'}}>Recommendation Rate</h3>
                  <p style={{fontSize: '2.5rem', fontWeight: 700, margin: '0 0 4px', color: '#ec4899'}}>{q3YesRate}%</p>
                  <p style={{color: 'var(--muted)', fontSize: '0.8rem', margin: 0}}>would recommend the site</p>
                </div>
              </div>

              {/* Feed of Cards */}
              <div style={{display: 'flex', flexDirection: 'column', gap: '20px'}}>
                {feedbacks.map((res, i) => (
                  <div key={i} className="card card-hoverable" style={{
                    padding: '24px',
                    border: '1px solid rgba(255, 255, 255, 0.06)',
                    background: 'rgba(20, 24, 45, 0.4)'
                  }}>
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '15px', flexWrap: 'wrap', gap: '15px' }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                        <span style={{ fontSize: '2.2rem' }}>
                          {res.evaluation_questionnaire.satisfaction === 5 ? '😍' :
                           res.evaluation_questionnaire.satisfaction === 4 ? '🙂' :
                           res.evaluation_questionnaire.satisfaction === 3 ? '😐' :
                           res.evaluation_questionnaire.satisfaction === 2 ? '🙁' : '😠'}
                        </span>
                        <div>
                          <Link href={`/instructor/student-detail?student=${res.username}`} style={{ fontSize: '1.15rem', color: 'var(--primary)', fontWeight: '700', textDecoration: 'none', display: 'inline-flex', alignItems: 'center', gap: '6px' }}>
                            <i className="fa-solid fa-user-circle" style={{opacity: 0.8}}></i>
                            {res.username}
                          </Link>
                          <p style={{ margin: 0, fontSize: '0.8rem', color: 'var(--muted)' }}>
                            Pre: {res.pre_score !== null ? `${res.pre_score}%` : '--'} | Post: {res.post_score !== null ? `${res.post_score}%` : '--'} ({res.delta !== null ? (res.delta >= 0 ? `+${res.delta}` : res.delta) : '0'}% gain)
                          </p>
                        </div>
                      </div>
                      <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap', alignItems: 'center' }}>
                        <span style={{ padding: '4px 10px', borderRadius: '12px', fontSize: '0.78rem', background: res.evaluation_questionnaire.q1_ai_helpful === 'Yes' ? 'rgba(16, 185, 129, 0.15)' : 'rgba(239, 68, 68, 0.15)', color: res.evaluation_questionnaire.q1_ai_helpful === 'Yes' ? '#34d399' : '#f87171' }}>
                          AI Helpful: {res.evaluation_questionnaire.q1_ai_helpful}
                        </span>
                        <span style={{ padding: '4px 10px', borderRadius: '12px', fontSize: '0.78rem', background: res.evaluation_questionnaire.q2_difficulty_appropriate === 'Yes' ? 'rgba(16, 185, 129, 0.15)' : 'rgba(239, 68, 68, 0.15)', color: res.evaluation_questionnaire.q2_difficulty_appropriate === 'Yes' ? '#34d399' : '#f87171' }}>
                          Difficulty OK: {res.evaluation_questionnaire.q2_difficulty_appropriate}
                        </span>
                        <span style={{ padding: '4px 10px', borderRadius: '12px', fontSize: '0.78rem', background: res.evaluation_questionnaire.q3_recommend === 'Yes' ? 'rgba(16, 185, 129, 0.15)' : 'rgba(239, 68, 68, 0.15)', color: res.evaluation_questionnaire.q3_recommend === 'Yes' ? '#34d399' : '#f87171' }}>
                          Recommend: {res.evaluation_questionnaire.q3_recommend}
                        </span>

                        <button
                          onClick={() => toggleCard(i)}
                          style={{
                            background: 'rgba(168, 85, 247, 0.12)',
                            border: '1px solid rgba(168, 85, 247, 0.25)',
                            borderRadius: '8px',
                            padding: '4px 10px',
                            color: '#c084fc',
                            fontSize: '0.78rem',
                            fontWeight: '600',
                            cursor: 'pointer',
                            display: 'inline-flex',
                            alignItems: 'center',
                            gap: '4px',
                            transition: 'all 0.2s'
                          }}
                        >
                          <i className={`fa-solid ${expandedCard[i] ? 'fa-eye-slash' : 'fa-eye'}`}></i>
                          {expandedCard[i] ? 'Hide Scores' : 'View Detail Scores'}
                        </button>
                      </div>
                    </div>

                    {/* Expandable detailed 1-5 ratings */}
                    {expandedCard[i] && (
                      <div style={{
                        marginTop: '15px',
                        marginBottom: '15px',
                        padding: '18px',
                        background: 'rgba(0, 0, 0, 0.2)',
                        border: '1px solid rgba(255, 255, 255, 0.05)',
                        borderRadius: '12px',
                        animation: 'fadeIn 0.2s'
                      }}>
                        {res.evaluation_questionnaire.q_math_clear === undefined ? (
                          <p style={{ margin: 0, color: 'var(--muted)', fontSize: '0.85rem', fontStyle: 'italic' }}>
                            <i className="fa-solid fa-circle-info"></i> Legacy student tester feedback. Individual numerical category metrics are not available for this record.
                          </p>
                        ) : (
                          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))', gap: '15px' }}>
                            <div style={{ borderLeft: '3px solid #22c55e', paddingLeft: '10px' }}>
                              <h5 style={{ margin: '0 0 5px 0', fontSize: '0.8rem', color: '#4ade80' }}>UX & Layout</h5>
                              <p style={{ margin: '3px 0', fontSize: '0.78rem', color: 'var(--muted)' }}>Clear Math: <strong style={{color:'#fff'}}>{res.evaluation_questionnaire.q_math_clear}/5</strong></p>
                              <p style={{ margin: '3px 0', fontSize: '0.78rem', color: 'var(--muted)' }}>Dark Mode: <strong style={{color:'#fff'}}>{res.evaluation_questionnaire.q_dark_mode}/5</strong></p>
                              <p style={{ margin: '3px 0', fontSize: '0.78rem', color: 'var(--muted)' }}>Easy Nav: <strong style={{color:'#fff'}}>{res.evaluation_questionnaire.q_navigation}/5</strong></p>
                            </div>
                            <div style={{ borderLeft: '3px solid #eab308', paddingLeft: '10px' }}>
                              <h5 style={{ margin: '0 0 5px 0', fontSize: '0.8rem', color: '#facc15' }}>Adaptive Engine</h5>
                              <p style={{ margin: '3px 0', fontSize: '0.78rem', color: 'var(--muted)' }}>Right Level: <strong style={{color:'#fff'}}>{res.evaluation_questionnaire.q_adaptation}/5</strong></p>
                              <p style={{ margin: '3px 0', fontSize: '0.78rem', color: 'var(--muted)' }}>Hints OK: <strong style={{color:'#fff'}}>{res.evaluation_questionnaire.q_hints}/5</strong></p>
                              <p style={{ margin: '3px 0', fontSize: '0.78rem', color: 'var(--muted)' }}>Improved: <strong style={{color:'#fff'}}>{res.evaluation_questionnaire.q_improvement}/5</strong></p>
                            </div>
                            <div style={{ borderLeft: '3px solid #ec4899', paddingLeft: '10px' }}>
                              <h5 style={{ margin: '0 0 5px 0', fontSize: '0.8rem', color: '#f472b6' }}>AI Intervention</h5>
                              <p style={{ margin: '3px 0', fontSize: '0.78rem', color: 'var(--muted)' }}>Walkthrough: <strong style={{color:'#fff'}}>{res.evaluation_questionnaire.q_ai_walkthrough}/5</strong></p>
                              <p style={{ margin: '3px 0', fontSize: '0.78rem', color: 'var(--muted)' }}>AI Tone: <strong style={{color:'#fff'}}>{res.evaluation_questionnaire.q_ai_tone}/5</strong></p>
                              <p style={{ margin: '3px 0', fontSize: '0.78rem', color: 'var(--muted)' }}>AI Length: <strong style={{color:'#fff'}}>{res.evaluation_questionnaire.q_ai_length}/5</strong></p>
                            </div>
                            <div style={{ borderLeft: '3px solid #3b82f6', paddingLeft: '10px' }}>
                              <h5 style={{ margin: '0 0 5px 0', fontSize: '0.8rem', color: '#60a5fa' }}>Psychology</h5>
                              <p style={{ margin: '3px 0', fontSize: '0.78rem', color: 'var(--muted)' }}>Timer Pause: <strong style={{color:'#fff'}}>{res.evaluation_questionnaire.q_timer_paused}/5</strong></p>
                              <p style={{ margin: '3px 0', fontSize: '0.78rem', color: 'var(--muted)' }}>Untimed: <strong style={{color:'#fff'}}>{res.evaluation_questionnaire.q_untimed}/5</strong></p>
                              <p style={{ margin: '3px 0', fontSize: '0.78rem', color: 'var(--muted)' }}>Confident: <strong style={{color:'#fff'}}>{res.evaluation_questionnaire.q_confidence}/5</strong></p>
                            </div>
                            <div style={{ borderLeft: '3px solid #a855f7', paddingLeft: '10px' }}>
                              <h5 style={{ margin: '0 0 5px 0', fontSize: '0.8rem', color: '#c084fc' }}>AI Review</h5>
                              <p style={{ margin: '3px 0', fontSize: '0.78rem', color: 'var(--muted)' }}>"Teach Me": <strong style={{color:'#fff'}}>{res.evaluation_questionnaire.q_teach_me}/5</strong></p>
                              <p style={{ margin: '3px 0', fontSize: '0.78rem', color: 'var(--muted)' }}>Study Plan: <strong style={{color:'#fff'}}>{res.evaluation_questionnaire.q_study_plan}/5</strong></p>
                            </div>
                          </div>
                        )}
                      </div>
                    )}

                    {res.evaluation_questionnaire.feedback_text ? (
                      <div style={{
                        background: 'rgba(0, 0, 0, 0.25)',
                        borderLeft: '4px solid #a855f7',
                        padding: '14px 18px',
                        borderRadius: '0 10px 10px 0',
                        color: '#f3f4f6',
                        fontSize: '0.95rem',
                        lineHeight: '1.6',
                        whiteSpace: 'pre-wrap'
                      }}>
                        {res.evaluation_questionnaire.feedback_text}
                      </div>
                    ) : (
                      <p style={{ margin: 0, color: 'var(--muted)', fontSize: '0.9rem', fontStyle: 'italic' }}>No written suggestions provided.</p>
                    )}
                  </div>
                ))}
              </div>
            </>
          )}
        </div>
      )}

      {activeTab === 'thesis' && (
        <div>
          {feedbacks.length === 0 ? (
            <div className="card" style={{textAlign: 'center', padding: '60px'}}>
              <i className="fa-solid fa-graduation-cap" style={{fontSize: '3rem', color: 'var(--muted)', marginBottom: '16px'}}></i>
              <h3>No Thesis Statistics Available</h3>
              <p style={{color: 'var(--muted)'}}>Once students complete evaluations, their academic analysis will be generated here.</p>
            </div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '30px' }}>
              
              {/* Thesis Analytics Overview Card */}
              <div className="card" style={{ padding: '24px', borderLeft: '5px solid #a855f7' }}>
                <h3 style={{ margin: '0 0 10px 0', color: '#fff', fontSize: '1.25rem' }}>🎓 Thesis Quantitative Survey Data</h3>
                <p style={{ margin: 0, color: 'var(--muted)', fontSize: '0.92rem', lineHeight: '1.5' }}>
                  Below is the computed statistical analysis for the 14 numerical questionnaire items (using a Likert scale of 1-5). 
                  Standard Deviation (S.D.) and positive Agreement rates (percentage of responses scoring 4 or 5) have been computed dynamically 
                  from the <strong>{feedbacks.length} student testers</strong>. You can copy the LaTeX code, Markdown tables, or CSV data below 
                  to import them directly into your thesis!
                </p>
              </div>

              {/* Detailed Academic Stats Table */}
              <div className="card" style={{ padding: 0, overflow: 'hidden' }}>
                <div style={{ padding: '20px 24px', borderBottom: '1px solid var(--border)', background: 'rgba(255,255,255,0.01)' }}>
                  <h4 style={{ margin: 0, color: '#a855f7', fontSize: '1.1rem' }}>Computed Survey Statistics</h4>
                </div>
                <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
                  <thead style={{ background: 'var(--highlight)', borderBottom: '1px solid var(--border)' }}>
                    <tr>
                      <th style={{ padding: '14px 20px', fontSize: '0.9rem' }}>Section</th>
                      <th style={{ padding: '14px 20px', fontSize: '0.9rem', width: '45%' }}>Survey Question Item</th>
                      <th style={{ padding: '14px 20px', fontSize: '0.9rem', textAlign: 'center' }}>Mean (1-5)</th>
                      <th style={{ padding: '14px 20px', fontSize: '0.9rem', textAlign: 'center' }}>S.D.</th>
                      <th style={{ padding: '14px 20px', fontSize: '0.9rem', textAlign: 'center' }}>Agreement (%)</th>
                    </tr>
                  </thead>
                  <tbody>
                    {detailedStats.map((item, idx) => (
                      <tr key={idx} style={{ borderBottom: '1px solid var(--border)' }}>
                        <td style={{ padding: '14px 20px', fontSize: '0.85rem', fontWeight: 600, color: 'var(--primary)' }}>
                          {item.section}
                        </td>
                        <td style={{ padding: '14px 20px', fontSize: '0.88rem', color: '#e5e7eb' }}>
                          {item.text}
                        </td>
                        <td style={{ padding: '14px 20px', fontSize: '0.95rem', fontWeight: 700, textAlign: 'center', color: '#a855f7' }}>
                          {item.mean}
                        </td>
                        <td style={{ padding: '14px 20px', fontSize: '0.9rem', textAlign: 'center', color: 'var(--muted)' }}>
                          {item.sd}
                        </td>
                        <td style={{ padding: '14px 20px', fontSize: '0.95rem', fontWeight: 700, textAlign: 'center', color: '#10b981' }}>
                          {item.agreement}%
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {/* Instant Thesis Exporters */}
              <div className="card" style={{ padding: '24px' }}>
                <h3 style={{ margin: '0 0 15px 0', color: '#fff', fontSize: '1.2rem' }}>📂 Rapid Exporters</h3>
                <p style={{ margin: '0 0 20px 0', color: 'var(--muted)', fontSize: '0.9rem' }}>
                  Select the required format, click copy, and paste it directly into your LaTeX thesis editor, Word processor, or Excel!
                </p>

                {/* Exporter tabs */}
                <div style={{ display: 'flex', gap: '10px', marginBottom: '15px' }}>
                  <button
                    onClick={() => setExporterTab('latex')}
                    style={{
                      padding: '8px 16px',
                      borderRadius: '8px',
                      border: exporterTab === 'latex' ? '1px solid #a855f7' : '1px solid rgba(255,255,255,0.08)',
                      background: exporterTab === 'latex' ? 'rgba(168, 85, 247, 0.15)' : 'transparent',
                      color: exporterTab === 'latex' ? '#c084fc' : '#9ca3af',
                      fontWeight: '600',
                      cursor: 'pointer',
                      fontSize: '0.85rem'
                    }}
                  >
                    LaTeX Code
                  </button>
                  <button
                    onClick={() => setExporterTab('markdown')}
                    style={{
                      padding: '8px 16px',
                      borderRadius: '8px',
                      border: exporterTab === 'markdown' ? '1px solid #a855f7' : '1px solid rgba(255,255,255,0.08)',
                      background: exporterTab === 'markdown' ? 'rgba(168, 85, 247, 0.15)' : 'transparent',
                      color: exporterTab === 'markdown' ? '#c084fc' : '#9ca3af',
                      fontWeight: '600',
                      cursor: 'pointer',
                      fontSize: '0.85rem'
                    }}
                  >
                    Markdown Table
                  </button>
                  <button
                    onClick={() => setExporterTab('csv')}
                    style={{
                      padding: '8px 16px',
                      borderRadius: '8px',
                      border: exporterTab === 'csv' ? '1px solid #a855f7' : '1px solid rgba(255,255,255,0.08)',
                      background: exporterTab === 'csv' ? 'rgba(168, 85, 247, 0.15)' : 'transparent',
                      color: exporterTab === 'csv' ? '#c084fc' : '#9ca3af',
                      fontWeight: '600',
                      cursor: 'pointer',
                      fontSize: '0.85rem'
                    }}
                  >
                    CSV (Excel)
                  </button>
                </div>

                {/* Exporter Area */}
                <div style={{ position: 'relative' }}>
                  {exporterTab === 'latex' && (
                    <>
                      <textarea
                        readOnly
                        value={getLaTeXCode()}
                        rows={12}
                        style={{
                          width: '100%',
                          background: 'rgba(0, 0, 0, 0.3)',
                          border: '1px solid rgba(255,255,255,0.08)',
                          borderRadius: '12px',
                          padding: '15px',
                          color: '#e5e7eb',
                          fontFamily: 'monospace',
                          fontSize: '0.85rem',
                          outline: 'none',
                          resize: 'none'
                        }}
                      />
                      <button
                        onClick={() => copyToClipboard(getLaTeXCode(), 'latex')}
                        style={{
                          position: 'absolute',
                          top: '12px',
                          right: '12px',
                          background: '#a855f7',
                          color: '#fff',
                          border: 'none',
                          padding: '6px 14px',
                          borderRadius: '6px',
                          fontWeight: '600',
                          fontSize: '0.8rem',
                          cursor: 'pointer',
                          boxShadow: '0 2px 8px rgba(168, 85, 247, 0.3)'
                        }}
                      >
                        {copyStatus === 'latex' ? 'Copied! 🎉' : 'Copy LaTeX'}
                      </button>
                    </>
                  )}

                  {exporterTab === 'markdown' && (
                    <>
                      <textarea
                        readOnly
                        value={getMarkdownCode()}
                        rows={12}
                        style={{
                          width: '100%',
                          background: 'rgba(0, 0, 0, 0.3)',
                          border: '1px solid rgba(255,255,255,0.08)',
                          borderRadius: '12px',
                          padding: '15px',
                          color: '#e5e7eb',
                          fontFamily: 'monospace',
                          fontSize: '0.85rem',
                          outline: 'none',
                          resize: 'none'
                        }}
                      />
                      <button
                        onClick={() => copyToClipboard(getMarkdownCode(), 'markdown')}
                        style={{
                          position: 'absolute',
                          top: '12px',
                          right: '12px',
                          background: '#a855f7',
                          color: '#fff',
                          border: 'none',
                          padding: '6px 14px',
                          borderRadius: '6px',
                          fontWeight: '600',
                          fontSize: '0.8rem',
                          cursor: 'pointer',
                          boxShadow: '0 2px 8px rgba(168, 85, 247, 0.3)'
                        }}
                      >
                        {copyStatus === 'markdown' ? 'Copied! 🎉' : 'Copy Markdown'}
                      </button>
                    </>
                  )}

                  {exporterTab === 'csv' && (
                    <>
                      <textarea
                        readOnly
                        value={getCSVCode()}
                        rows={12}
                        style={{
                          width: '100%',
                          background: 'rgba(0, 0, 0, 0.3)',
                          border: '1px solid rgba(255,255,255,0.08)',
                          borderRadius: '12px',
                          padding: '15px',
                          color: '#e5e7eb',
                          fontFamily: 'monospace',
                          fontSize: '0.85rem',
                          outline: 'none',
                          resize: 'none'
                        }}
                      />
                      <button
                        onClick={() => copyToClipboard(getCSVCode(), 'csv')}
                        style={{
                          position: 'absolute',
                          top: '12px',
                          right: '12px',
                          background: '#a855f7',
                          color: '#fff',
                          border: 'none',
                          padding: '6px 14px',
                          borderRadius: '6px',
                          fontWeight: '600',
                          fontSize: '0.8rem',
                          cursor: 'pointer',
                          boxShadow: '0 2px 8px rgba(168, 85, 247, 0.3)'
                        }}
                      >
                        {copyStatus === 'csv' ? 'Copied! 🎉' : 'Copy CSV'}
                      </button>
                    </>
                  )}
                </div>
              </div>

            </div>
          )}
        </div>
      )}

    </div>
  );
}
