import mongoose from 'mongoose';

const UserSchema = new mongoose.Schema({
  username: { type: String, required: true, unique: true },
  email: { type: String, unique: true, sparse: true },
  password_hash: { type: String, required: true },
  role: { type: String, enum: ['student', 'instructor'], default: 'student' },
  profile_configured: { type: Boolean, default: false },
  learning_profile: { type: mongoose.Schema.Types.Mixed, default: {} },
  notifications: [{
    message: String,
    timestamp: { type: Date, default: Date.now },
    read: { type: Boolean, default: false }
  }],
  
  // Topic-specific states inside MongoDB!
  brain_state_fractions: { type: mongoose.Schema.Types.Mixed, default: {} },
  diagnostic_index_fractions: { type: Number, default: 0 },
  diagnostic_correct_fractions: { type: Number, default: 0 },
  diagnostic_time_sum_fractions: { type: Number, default: 0 },
  diagnostic_completed_fractions: { type: Boolean, default: false },
  current_action_fractions: { type: mongoose.Schema.Types.Mixed, default: null },
  attempt_count_current_action_fractions: { type: Number, default: 1 },
  seen_questions_fractions: { type: [String], default: [] },
  questions_since_last_upload_fractions: { type: Number, default: 0 },
  topic_intro_seen_fractions: { type: Boolean, default: false },
  mastery_streak_fractions: { type: Number, default: 0 },
  master_validations_fractions: { type: Number, default: 0 },
  topic_graduated_fractions: { type: Boolean, default: false },
  
  brain_state_exponents: { type: mongoose.Schema.Types.Mixed, default: {} },
  diagnostic_index_exponents: { type: Number, default: 0 },
  diagnostic_correct_exponents: { type: Number, default: 0 },
  diagnostic_time_sum_exponents: { type: Number, default: 0 },
  diagnostic_completed_exponents: { type: Boolean, default: false },
  current_action_exponents: { type: mongoose.Schema.Types.Mixed, default: null },
  attempt_count_current_action_exponents: { type: Number, default: 1 },
  seen_questions_exponents: { type: [String], default: [] },
  questions_since_last_upload_exponents: { type: Number, default: 0 },
  topic_intro_seen_exponents: { type: Boolean, default: false },
  mastery_streak_exponents: { type: Number, default: 0 },
  master_validations_exponents: { type: Number, default: 0 },
  topic_graduated_exponents: { type: Boolean, default: false },
  
  brain_state_geometry: { type: mongoose.Schema.Types.Mixed, default: {} },
  diagnostic_index_geometry: { type: Number, default: 0 },
  diagnostic_correct_geometry: { type: Number, default: 0 },
  diagnostic_time_sum_geometry: { type: Number, default: 0 },
  diagnostic_completed_geometry: { type: Boolean, default: false },
  current_action_geometry: { type: mongoose.Schema.Types.Mixed, default: null },
  attempt_count_current_action_geometry: { type: Number, default: 1 },
  seen_questions_geometry: { type: [String], default: [] },
  questions_since_last_upload_geometry: { type: Number, default: 0 },
  topic_intro_seen_geometry: { type: Boolean, default: false },
  mastery_streak_geometry: { type: Number, default: 0 },
  master_validations_geometry: { type: Number, default: 0 },
  topic_graduated_geometry: { type: Boolean, default: false },

  brain_state_algebra: { type: mongoose.Schema.Types.Mixed, default: {} },
  diagnostic_index_algebra: { type: Number, default: 0 },
  diagnostic_correct_algebra: { type: Number, default: 0 },
  diagnostic_time_sum_algebra: { type: Number, default: 0 },
  diagnostic_completed_algebra: { type: Boolean, default: false },
  current_action_algebra: { type: mongoose.Schema.Types.Mixed, default: null },
  attempt_count_current_action_algebra: { type: Number, default: 1 },
  seen_questions_algebra: { type: [String], default: [] },
  questions_since_last_upload_algebra: { type: Number, default: 0 },
  topic_intro_seen_algebra: { type: Boolean, default: false },
  mastery_streak_algebra: { type: Number, default: 0 },
  master_validations_algebra: { type: Number, default: 0 },
  topic_graduated_algebra: { type: Boolean, default: false },
}, { timestamps: true });

export default mongoose.models.User || mongoose.model('User', UserSchema);
